name: Test

on:
  workflow_dispatch: {}
  push: {}

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    continue-on-error: true

    strategy:
      matrix:
        python: ["3.8", "3.10", "3.12"]
        torch: ["1.13", "2.2", "2.5"]
        exclude:
          - python: "3.8"
            torch: "2.5"
          - python: "3.12"
            torch: "1.13"

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}

      - name: Install Package
        run: |
          pip install torch~=${{ matrix.torch }}.0
          pip install .[dev]

      - name: Test
        run: |
          pytest --cov --cov-report term-missing --cov-fail-under 90 tests/
          ruff format .
          isort --diff .
          ruff check .
